Model submission for marble_husky sensor configuration 6 by MARBLE
osrf/subt pull request #850
Opened 2021-03-29 22:19 UTC by bfotheri

This sensor configuration represents the vehicle MARBLE is presently using and plans to use for the final circuit event this fall. It differs from previous sensor configurations in that it now has 4 RGB cameras facing orthogonal directions, a vertical OUSTER LIDAR, and the front two D435i's have been replaced with Pico Flexx cameras. 

I need to discuss with my team but apparently validation data for this and previous configurations were submitted to OSRF in the fall of 2020 by our teammate Kyle Harlow on behalf of MARBLE. I will ask him where that is, but on your end could you also check if that was received? Thank you guys!

2021-03-30 14:25 UTC, angelacmaio commented
Can you upload the validation data to the DARPA Box link that has since been provided in the [Model Preparation Guide](https://subtchallenge.com/resources/Simulation_Model_Preparation_Guide.pdf)?

2021-03-31 00:03 UTC, bfotheri commented
Validation data has been successfully uploaded to the link provided in the Model Preparation Guide. File is named "MARBLE_HUSKY.zip"

2021-04-01 13:43 UTC, bfotheri commented
Also, MARBLE is currently using this vehicle as a marsupial pair in preparation for the final circuit systems event. I have local changes to competition.ign that allow this locally, but was unsure of the procedure for merging those in. Should I add those marsupial changes and commit them for review or should some verification/discussion happen prior?

2021-05-07 17:14 UTC, acschang requested changes
The initial assessment of this sensor configuration submission is complete, however there are some issues to resolve before this sensor configuration can be merged and utilized in a competitive setting:

- [ ] Please update the Ouster LIDAR and Pico Flexx sensor parameters per the in-line comments.
- [ ] Please verify the mass listed in the `specifications.md` file matches the total mass in the `model.sdf`.
- [ ] Please add the `wheel_slip` plugin section to the `spawner.rb` file.
- [ ] Please clarify if the sensor suite cost for sensor config 6 matches the value in the `specifications.md` file.
- [ ] Please update the sensor specifications link for the FLIR camera in the `specifications.md` file.
- [x] Please add all missing components to the RViz visualization.
- [ ] Please update `vehicle_topics.launch` file in sensor config 3 to include transports for the thermal camera and the `breadcrumbs_remaining` transport for compatibility with sensor config 4.

Please address the issues noted above and add commits to this pull request as soon as possible. The submissions are expected to be incorporated into the SubT Virtual Testbed

2021-05-07 17:54 UTC, dan-riley commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                <max_angle>0.2897</max_angle>
> The OS1-64's vertical field of view is +-22.5 degrees. Please update the `min_angle` and `max_angle` parameters here to: `0.392699`.

We have Gen 1 OS-1's, which only have a 33 degree vfov.

2021-05-07 17:59 UTC, dan-riley commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                <max_angle>0.2897</max_angle>
We have Gen 1 OS-1's, which only have a 33 degree vfov.

2021-05-10 19:00 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +              <stddev>0.015</stddev>
Value appears to already be 0.015, please clarify

2021-05-10 19:01 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +              <resolution>0.003</resolution>
Updated, will push soon

2021-05-10 19:01 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +              <stddev>0.015</stddev>
Value appears to already be 0.015, please clarify

2021-05-10 19:02 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +              <resolution>0.003</resolution>
Updated, will push soon

2021-05-10 19:08 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                    <fx>59.55</fx>
That's correct, updated, will push soon.

2021-05-10 19:08 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                    <fx>59.55</fx>
That's correct, updated, will push soon.

2021-05-10 19:14 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_6/specifications.md
> +    * Explanation of sensor parameter derivations:
Updated, will push soon. Validation data was uploaded to the following [location](https://github.com/osrf/subt/pull/850#issuecomment-810305095) referenced in the comment , for the time being but is not in youtube or google drive format yet

2021-05-10 19:28 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_6/specifications.md
> +* Sensor suite: $12,000
Updated, will push soon

2021-05-10 19:30 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_3/launch/vehicle_topics.launch
> +  <group ns="$(arg name)">
Updated, will push soon

2021-05-10 19:33 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_3/launch/vehicle_topics.launch
> +    </group>
Updated, will push soon

2021-05-10 19:34 UTC, bfotheri commented on submitted_models/marble_husky_sensor_config_3/launch/vehicle_topics.launch
> +
updated, will push soon

2021-05-18 19:29 UTC, acschang commented on submitted_models/marble_husky_sensor_config_3/.vscode/c_cpp_properties.json
> +{
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:29 UTC, acschang commented on submitted_models/marble_husky_sensor_config_3/.vscode/settings.json
> +{
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:30 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/specifications.md
> +* Sensor suite: $12,000
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:31 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/specifications.md
> +    * Explanation of sensor parameter derivations:
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:32 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/specifications.md
> +  * FLIR Backfly Camera - https://www.edmundoptics.com/p/bfly-pge-05s2c-cs-13-blackflyreg-poe-gige-color-camera/30315/
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:32 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                    <fx>59.55</fx>
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:36 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                <max_angle>0.2897</max_angle>
The [provided documentation](https://ouster.com/products/os1-lidar-sensor/) indicates the VFoV should be +-22.5 degrees.  Is the included documentation incorrect?
![Screenshot from 2021-05-18 15-35-48](https://user-images.githubusercontent.com/61025344/118712448-cb8c4880-b7ee-11eb-8a3a-ffc4de83fe38.png)

2021-05-18 19:37 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +              <resolution>0.003</resolution>
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:37 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +              <resolution>0.003</resolution>
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:37 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                    <fx>59.55</fx>
Fixed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:38 UTC, acschang commented on submitted_models/marble_husky_sensor_config_3/launch/vehicle_topics.launch
> +  <group ns="$(arg name)">
Added in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:39 UTC, acschang commented on submitted_models/marble_husky_sensor_config_3/launch/vehicle_topics.launch
> +    </group>
Added in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 19:56 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                <max_angle>0.2897</max_angle>
So it appears that the Ouster website is displaying Gen 2 sensor parameters by default and Gen 1's parameters are listed [elsewhere](https://data.ouster.io/downloads/datasheets/datasheet-gen1-v2p0-os1.pdf).  I'll update the link to the documentation in this case however the documentation links are definitely deprecated for other Ouster Gen 1 sensors in the repository now.

2021-05-18 20:03 UTC, acschang commented
Continued in #918

2021-05-18 20:03 UTC, closed without merging

2021-05-18 20:07 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                <max_angle>0.2897</max_angle>
Addressed in https://github.com/osrf/subt/pull/918/commits/fff0990fcc17a5ea93d5a73a87bb58bf88228b7c

2021-05-18 20:07 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +                <max_angle>0.2897</max_angle>
Addressed in https://github.com/osrf/subt/pull/918/commits/fff0990fcc17a5ea93d5a73a87bb58bf88228b7c based upon https://github.com/osrf/subt/pull/850#discussion_r624578255

2021-05-18 20:09 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/launch/spawner.rb
> +      <plugin filename="libignition-gazebo-breadcrumbs-system.so"
Addressed in https://github.com/osrf/subt/pull/850/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8

2021-05-18 20:40 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +              <stddev>0.015</stddev>
I meant to type `0.01` to meet the repository standard however I made a typo.

Fixed in https://github.com/osrf/subt/pull/918/commits/c540270ac30d3bfbda3ab2f00b5ad217bf5b4abe

2021-05-18 20:40 UTC, acschang commented on submitted_models/marble_husky_sensor_config_6/model.sdf
> +              <stddev>0.015</stddev>
Fixed in https://github.com/osrf/subt/pull/918/commits/c540270ac30d3bfbda3ab2f00b5ad217bf5b4abe

2021-05-18 20:48 UTC, acschang commented on submitted_models/marble_husky_sensor_config_3/model.config
> +     CU's husky config with 3 D435i RGBD cameras, a pan-tilt turret, the Ouster OS1 64 channel lidar,
Fixed in https://github.com/osrf/subt/pull/918/commits/a21c326a0059be38dd5920bf592e2b6e2d5af2d8