Spot: Validation data
osrf/subt pull request #913
Opened 2021-05-13 00:54 UTC by peci1

We've finally got our hands on a real Spot, so here are the validation data.

We computed the battery endurance from the estimated percentage published by the driver which might be better suitable for linear extrapolation.

2021-05-14 15:18 UTC, peci1 commented
Today we measured the total mass of our sensor config. It came out about 3 kg heavier than what was estimated in the model, so I also updated the total mass of the model (this discrepancy is mostly because we found out that the internal Spot battery is not good enough to power both the robot and the sensor pack for an hour, so we decided to add a separate battery for the sensor pack).

2021-06-14 17:58 UTC, acschang requested changes

2021-06-14 17:58 UTC, acschang commented on submitted_models/ctu_cras_norlab_spot_sensor_config_1/model.sdf
> +        <attenuation>ign sdf -p
Is this line intended?

2021-06-14 18:24 UTC, acschang approved these changes

2021-06-14 18:39 UTC, acschang commented on submitted_models/ctu_cras_norlab_spot_sensor_config_1/model.sdf
> +        <attenuation>ign sdf -p
Fixed in https://github.com/osrf/subt/pull/953/commits/dd1bc50e8fed275918072026f6179aa274882a50

2021-06-14 18:39 UTC, acschang commented
Continued in #953

2021-06-14 18:39 UTC, closed without merging